Set up for single flashing No Kernel:
Signed-off-by: Eliminater74 <eliminater74@gmail.com>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -131,16 +131,18 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.pnpmgr)" == 2 ]; then
   		mount -o remount,ro -t auto /system;
 fi;
 
-ui_print "[Nebula] Installing Kernel, Please wait...";
-for i in $($bb --list); do
-  $bb ln -s $bb /tmp/anykernel/bin/$i;
-done;
-if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
-  abort "Recovery busybox setup failed. Aborting...";
-fi;
-PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
-if [ $? != "0" ]; then
-  abort;
+if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.kernel)" == 1 ]; then
+			ui_print "[Nebula] Installing Kernel, Please wait...";
+			for i in $($bb --list); do
+  		$bb ln -s $bb /tmp/anykernel/bin/$i;
+			done;
+			if [ $? != 0 -o -z "$(ls /tmp/anykernel/bin)" ]; then
+  		abort "Recovery busybox setup failed. Aborting...";
+			fi;
+			PATH="/tmp/anykernel/bin:$PATH" $bb ash /tmp/anykernel/anykernel.sh $2;
+			if [ $? != "0" ]; then
+  		abort;
+			fi;
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.modules)" == 1 ]; then
@@ -168,12 +170,23 @@ if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.eas_support)" == 1 ]; then
 						chmod 0644 /system/lib64/libcutils.so;
 					else
 						ui_print "[EAS] LOS Based Rom Detected: "
-						cp -f /tmp/anykernel/system/bin/init.nebula.sh /system/bin/;
+						cp -f /tmp/anykernel/system/etc/init.nebula.sh /system/etc/;
 						cp -f /tmp/anykernel/system/bin/init.foreground.sh /system/bin/;
 				 fi
 		chmod 0755 /system/bin/init.foreground.sh;
-		chmod 0755 /system/bin/init.nebula.sh;					
+		chmod 0755 /system/etc/init.nebula.sh;					
 		mount -o remount,ro -t auto /system;		
+fi;
+
+if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.aptxhd)" == 1 ]; then
+		ui_print "[Nebula] AptXHD: Entergizing.......";
+		ui_print " ";
+		mount -o remount,rw -t auto /system;
+				cp -rf /tmp/anykernel/system/vendor/lib/* /system/vendor/lib/;
+				cp -rf /tmp/anykernel/system/vendor/lib/hw/* /system/vendor/lib/hw/;
+				set_perm_recursive 0 0 0755 0755 /system/vendor/lib;
+				set_perm_recursive 0 0 0755 0755 /system/vendor/lib/hw;
+				mount -o remount,ro -t auto /system;		
 fi;
 
 if [ "$(file_getprop /tmp/anykernel/anykernel.sh do.boost_scripts)" == 1 ]; then
@@ -222,8 +235,8 @@ ui_print "                     _\|/_                    ";
 ui_print "                     (o o)                     ";
 ui_print "+-----------------oOO-(_)-OOo-----------------+";
 ui_print "|         Device: HTC10                       |";
-ui_print "|         Kernel: EAS Edition                 |";
-ui_print "|         Update: 02/01/2017                  |";
+ui_print "|         Extra: AptXHD                       |";
+ui_print "|         Update: 02/15/2017                  |";
 ui_print "|                                             |";
 ui_print "|     Developed By,                           |";
 ui_print "|              XDA: Eliminater74              |";
